name: Build

on:
  push:
    branches:
      - "*"

jobs:
  matrix_prep:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: ''
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: nelonoel/branch-name@v1.0.1
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
        with:
          filter: '[?runOn==`${{ env.BRANCH_NAME }}` || runOn==`always`]'

  build-n-test:
    needs: matrix_prep
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.py_version }}"
      - name: Install dependencies
        run: |
          pip3 install pipenv
          sed -i 's/3.8/${{ matrix.py_version }}/g' Pipfile
          pipenv install --dev --ignore-pipfile --deploy
      - name: Make docs
        run: |
          cd docs
          pipenv run make clean
          pipenv run make html
